name: Hermes

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: debug

jobs:
  build_android:
    runs-on: [self-hosted, macOS, build]

    # Wymagany do pobrania aktualnych zmian
    steps:
    - uses: actions/checkout@v3

    - name: Testowanie
      run: echo Jestem testem!
